language: java
jdk:
  - oraclejdk8
script:
  - cd deploy_pom
  # - mvn clean -X
  - mvn deploy --settings settings.xml
branches:
  only:
  - master

# See https://github.com/travis-ci/travis-ci/issues/6593, sometime Maven Central isn't accessible to non-sudo users
sudo: true 
