language: java
jdk:
  - oraclejdk8
script:
  - mkdir --parents "$HOME/.m2"
  - cd deploy_pom
  # - mvn clean -X
  - mvn deploy --settings settings.xml
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
